[package]
name = "leda"
version = "0.1.0"
edition = "2021"

[lib]
name = "leda"
crate-type = ["lib", "cdylib"]

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
url = "2.2.2"
thiserror = "1.0.30"